### PR TITLE
push/pop & set_random_phase

### PR DESCRIPTION
**Pull request by lee30sonia**

### CODE REVIEW

**Comment by hriener** [comment]
Thanks. Looks very good.

- There is something wrong with the indentation in the `solve` method of bsat2
- Would be also good to mention the new interface methods in the documentation and the changelog.

**Comment by hriener** [comment]
Thanks! Is it ready to be merged?

**Comment by lee30sonia** [comment]
> Thanks! Is it ready to be merged?

Yes, if there's no other comments.

**Comment by hriener** [comment]
Thanks!

**Pull request merged**
